services:
  postgres:
    image: 'postgres:16'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=todoapi'
      - 'POSTGRES_PASSWORD=todoapi'
      - 'POSTGRES_DB=todoapi_db'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'
volumes:
  postgres_data: